service: cam-dienstplan 
provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  stage: prod
  architecture: arm64
  memorySize: 128
  apiGateway:
    shouldStartNameWithService: true
functions:
  dienstplan:
    handler: handler.dienstplan
    events:
     - http:
         path: getSchedule
         method: get